### ISSUE TITLE
baseUrl inside source is not working

### ISSUE THREAD

**Issue by ritesh-malav** [iou90/react-native-autoheight-webview#65]
I was using "react-native-autoheight-webview": "^0.5.1" version and baseUrl inside source was working but after upgrading to latest version it does not seems to be working.

**Comment by ritesh-malav** [comment]
Android

**Comment by iou90** [comment]
And everything is working properly except the baseUrl?

在 2018年7月29日，02:17，ritesh-malav <notifications@github.com<mailto:notifications@github.com>> 写道：


Android

**Comment by ritesh-malav** [comment]
Yes

**Comment by iou90** [comment]
Should fixed at @0.10.1

**Comment by ritesh-malav** [comment]
Thank you for such quick resolution.

**Comment by ritesh-malav** [comment]
Sorry for reopening but it is still not working. somehow i did not update the correct the version and thought it has been fixed.

**Comment by ritesh-malav** [comment]
Actually i get it now. It has been because of the baseUrl changes in the latest release now i am using the latest version where base url is file:///android_asset/web/ where i was mentioning base url as file:///android_asset/some_folder/ so it is not able to get it properly. What is the resolution from your side because user can mention baseUrl as how he want. So i don't think we shall restrict the user with url /web

**Comment by iou90** [comment]
Please try @0.10.2

**Comment by ritesh-malav** [comment]
Sure I will update and check It.
